# Generated by Django 5.2.10 on 2026-01-27 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='notes',
        ),
        migrations.AddField(
            model_name='project',
            name='address',
            field=models.TextField(blank=True, verbose_name='Ад'),
        ),
        migrations.AddField(
            model_name='project',
            name='documents',
            field=models.TextField(blank=True, verbose_name='Документы'),
        ),
    ]
