# Generated by Django 5.2.10 on 2026-01-28 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_notes_project_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='documents',
        ),
        migrations.AddField(
            model_name='project',
            name='document_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на Документы'),
        ),
        migrations.AlterField(
            model_name='project',
            name='address',
            field=models.TextField(blank=True, verbose_name='Адрес'),
        ),
    ]
