server {
    listen 80;
    # Если есть домен, напишите его вместо localhost, если нет - оставьте localhost или IP
    server_name localhost;

    # 1. Фронтенд (Vue) - отдаем просто файлы
    location / {
        root /app/frontend_dist; # Путь внутри контейнера Nginx (см. docker-compose)
        index index.html;
        try_files $uri $uri/ /index.html; # Важно для роутера Vue
    }

    # 2. Бэкенд (API) - отправляем в Django
    location /api/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 3. Админка и статика Django
    location /admin/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
    }

    location /static/ {
        alias /app/static/;
    }

    location /media/ {
        alias /app/media/;
    }
}
